book_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('listbooks/', views.list_books, name='list_books'),
    path('bookregister/', views.book_register, name='book_register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
  title = models.CharField(max_length=200)
  author = models.CharField(max_length=100)
  published_date = models.DateField()
  book_cover = models.ImageField(upload_to='book_covers/', blank=True, null=True, default="book_covers/vazio.jpg")
  

  # def __str__(self):
  #   return self.title, self.author

books/forms.py
from django import forms
from .models import Book


class RegistroForm(forms.ModelForm):
  class Meta:
    model = Book
    fields = ['title', 'author', 'published_date', 'book_cover']

# class LivroForm(forms.Form):
#   title = forms.CharField(max_length=100)
#   author = forms.CharField(max_length=100)
#   published_date = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'))
#   book_cover = forms.ImageField()

books/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .models import Book
from .forms import RegistroForm
# Create your views here.

def index(request):
  template = loader.get_template('book_list.html')
  context = {
    'title': 'Home pag'
  }

  return HttpResponse(template.render(context, request))

def list_books(request):
  template = loader.get_template('book_list.html')

  books = Book.objects.all()

  context = {
    'books': books,
    'title': 'Lista de livros',
  }
  

  return HttpResponse(template.render(context, request))

def book_register(request):
  if request.method == 'POST':
    form = RegistroForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect('list_books')
    
  else:
    form = RegistroForm()

    


  template = loader.get_template('book_register.html')
  context={
    'title': 'Cadastro de livros',
    'form':form,
  }

  return HttpResponse(template.render(context, request))

books/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
  <link rel="stylesheet" href="{% static 'book/css/style.css' %}">
  <title>{% block title %}
    Biblioteca Virtual
    {% endblock %}</title>
</head>

<body>
  <nav id="navegacao">
    <a href=" {% url 'index' %}">Home</a>
    <a href="{% url  'list_books' %}">Book List</a>
    <a href="{% url  'book_register' %}">book register</a>
    <a href="/admin">Admin</a>

  </nav>
  {% block content %}

  {% endblock %}
</body>

</html>

books/templates/book_list.html
{% extends "base.html" %}
{% block title %} {{title}} {% endblock %}

{% block content %}

<h1 id="titulo-pag">{{title}}</h1>

<div class="flexP">

  {% for book in books %}

    <div class="card" >
      <div class="container-img">
        <img src="{{book.book_cover.url}}" alt="{{book.title}}">        
      </div>
      <h4> {{book.title}} </h4>
      <p> <strong> Autor:</strong>  {{book.author}} </p>
      <p><strong>Data de Publicação:</strong> {{book.published_date}} </p>
      <!-- <button class="btn">Saiba Mais</button> -->
    </div>  
  
  {% endfor %}

</div>

{% endblock %}

books/templates/book_register.html
{% extends "base.html" %}
{%block title%} {{title}} {%endblock%}

{% block content %}
<h1 id="titulo-pag">{{title}}</h1>

<!-- <form action="" method="post">
  {% csrf_token %}
  <label for="id_title"> Titulo:</label>
  {{form.title}}

  <label for="id_author"> Autor:</label>
  {{form.author}}

  <label for="id_published_date"> Data Public:</label>
  {{form.published_date}}

  <label for="id_book_cover"> Capa:</label>
  {{form.book_cover}}

  <button type="submit">Cadastrar</button>

</form> -->

<form action="" method="post">
  {% csrf_token %}
  {{form}}

  <button type="submit">Cadastrar</button>

</form>




{% endblock %}

books/templates/index.html
{% extends "base.html" %}
{% block title %} {{title}} {% endblock %}

{% block content %}

<h1 id="titulo-pag">{{title}}</h1>


</div>

{% endblock %}